name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore LauncherGenerator
    - name: Publish (linux-x64)
      run: dotnet publish -p:PublishSingleFile=true --self-contained true -r linux-x64 -c Release LauncherGenerator
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: LauncherGenerator
        path: LauncherGenerator/bin/Release/netcoreapp5.0/linux-x64/publish/*
