name: Build on Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore LauncherGenerator/LauncherGenerator.csproj
    - name: Build
      run: dotnet publish -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=true -r linux-x64 LauncherGenerator/ --no-restore
    - uses: actions/upload-artifact@v2
      with:
        name: LauncherGenerator_linux-x64
        path: LauncherGenerator/bin/Release/netcoreapp3.1/linux-x64/publish/LauncherGenerator
